<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="frmInformedecliente.aspx.cs" Inherits="Presentacion.frmInformedecliente" %>
<%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
    .style1
    {
        width: 100%;
    }
    .style2
    {
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <table class="style1">
    <tr>
        <td class="style2" colspan="2">
            PARAMETROS</td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style2" rowspan="3">
            &nbsp;</td>
        <td class="style2">
            Rubro&nbsp;
            <asp:DropDownList ID="cbrubro" runat="server" Height="18px" Width="297px">
            </asp:DropDownList>
            <asp:LinkButton ID="LinkButton1" runat="server" onclick="LinkButton1_Click">Resumen Ejecutivo</asp:LinkButton>
        </td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style2">
            <asp:RadioButton ID="rbnatural" runat="server" Text="Natural" />
            <asp:RadioButton ID="rbjuridico" runat="server" Text="Juridico" />
            <asp:RadioButton ID="rbtodos" runat="server" Text="Todos" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnbuscar" runat="server" onclick="btnbuscar_Click" 
                style="margin-left: 0px" Text="Buscar" />
        </td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style2">
            <asp:ScriptManager ID="ScriptManager1" runat="server">
            </asp:ScriptManager>
        </td>
        <td>
            &nbsp;</td>
        <td>
            &nbsp;</td>
    </tr>
    <tr>
        <td class="style2">
            <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" 
                ontreenodedatabound="TreeView1_TreeNodeDataBound" ShowLines="True" 
                style="margin-top: 0px">
                <Nodes>
                    <asp:TreeNode 
                        Text="Informes" Value="Informes">
                        <asp:TreeNode NavigateUrl="~/frmreportes.aspx?nro_reporte=2" Text="Clientes" 
                            Value="Clientes">
                            <asp:TreeNode NavigateUrl="~/frmInformedecliente.aspx?nro_reporte=1" 
                                Text="Natural" Value="natural"></asp:TreeNode>
                            <asp:TreeNode NavigateUrl="~/frmInformedecliente.aspx?nro_reporte=4" 
                                Text="Juridico" Value="Juridico"></asp:TreeNode>
                        </asp:TreeNode>
                        <asp:TreeNode Text="Rubros" Value="Rubros"></asp:TreeNode>
                        <asp:TreeNode Text="Productos" Value="Productos"></asp:TreeNode>
                        <asp:TreeNode Text="Pedidos" Value="Pedidos"></asp:TreeNode>
                    </asp:TreeNode>
                </Nodes>
            </asp:TreeView>
        </td>
        <td colspan="3">
            <rsweb:ReportViewer ID="ReportViewer1" runat="server" Width="796px" 
                style="margin-right: 0px">
            </rsweb:ReportViewer>
        </td>
    </tr>
</table>
</asp:Content>
